/**
 * This file is auto-generated by Amplitude.
 * To update run 'ampli pull visual-studio-code'
 *
 * Works with versions ^2.0.8 of @itly/sdk and @itly/plugin's
 * https://www.npmjs.com/search?q=%40itly
 */

/* tslint:disable */
/* eslint-disable */
import {
  ItlyNode,
  Options as OptionsBase,
  Event as EventBase,
  Plugin,
  Environment as EnvironmentBase,
  Properties as PropertiesBase,
  ValidationResponse as ValidationResponseBase,
  CallOptions as CallOptionsBase,
  PluginCallOptions as PluginCallOptionsBase,
} from '@itly/sdk';
import SchemaValidatorPlugin from '@itly/plugin-schema-validator';

export type Options = OptionsBase;
export type Environment = EnvironmentBase;
export type Event = EventBase;
export type Properties = PropertiesBase;
export type ValidationResponse = ValidationResponseBase;
export type CallOptions = CallOptionsBase;
export type PluginCallOptions = PluginCallOptionsBase;
export { Plugin, Validation, Loggers } from '@itly/sdk';

export interface AliasOptions extends CallOptions {
}

export interface IdentifyOptions extends CallOptions {
}

export interface GroupOptions extends CallOptions {
}

export interface PageOptions extends CallOptions {
}

export interface TrackOptions extends CallOptions {
}

export interface IdentifyProperties {
  /**
   * Applies to non-user identities, such as Snyk Orgs
   */
  isNonUser?: boolean;
  /**
   * Whether or not the user belongs to the Snyk org (determined by the email address ending with @snyk.io)
   */
  is_snyk?: boolean;
  /**
   * query utm_medium
   */
  utm_medium?: string;
  /**
   * Name of the user
   */
  name?: string;
  /**
   * query utm_medium
   */
  utmMedium?: string;
  /**
   * query utm_campaign
   */
  utm_campaign?: string;
  /**
   * Link to access more information about the user
   */
  adminLink?: string;
  /**
   * Timestamp of user creation
   */
  createdAt?: number;
  /**
   * query utm_source
   */
  utmSource?: string;
  /**
   * Email address for the user
   */
  email?: string;
  /**
   * when a User record is an actual user or when it’s a “service account”
   */
  accountType?: "user" | "service" | "app-instance";
  /**
   * Auth provider (login method)
   */
  authProvider?: string;
  /**
   * Whether or not the user belongs to the Snyk org (determined by the email address ending with @snyk.io)
   */
  isSnyk?: boolean;
  /**
   * query utm_source
   */
  utm_source?: string;
  /**
   * Timestamp of user creation
   */
  created_at?: number;
  /**
   * Auth provider (login method)
   */
  auth_provider?: string;
  /**
   * Whether or not the user has their first project imported
   */
  hasFirstProject?: boolean;
  /**
   * Whether or not the user should be considered a Snyk administrator
   */
  isSnykAdmin?: boolean;
  /**
   * Public ID of user
   */
  user_id?: string;
  /**
   * Whether or not the user has their first integration set up
   */
  hasFirstIntegration?: boolean;
  /**
   * Link to access more information about the user
   */
  admin_link?: string;
  /**
   * Username of the user
   */
  username?: string;
  /**
   * query utm_campaign
   */
  utmCampaign?: string;
}

export interface GroupProperties {
  /**
   * ID that is used in conjunction with a groupType to specify an Org or a Group association: {groupId: 1234, groupType: "org"}
   */
  groupId?: string;
  /**
   * The display name of the org
   */
  name?: string;
  /**
   * The internal name (org.name) of the org
   */
  internalName?: string;
  /**
   * Key that is used to specify the name of the Segment Group that a groupId is being set for.
   */
  groupType?: "org" | "group" | "account";
  /**
   * The plan of the org
   */
  plan?: string;
  /**
   * The name of the group associated with the org
   */
  groupName?: string;
  /**
   * The types of projects in the org
   */
  projectTypes?: string[];
}

export interface PageProperties {
  /**
   * The name of the package
   */
  package?: string;
  /**
   * Query parameters in url.
   */
  search?: string;
  /**
   * The url of the page.
   */
  url?: string;
  /**
   * The page title.
   */
  title?: string;
  /**
   * The canonical path of the page
   */
  path?: string;
  /**
   * Name of the ecosystem (npm|python|docker...)
   */
  ecosystem?: string;
  /**
   * The page that linked to this page.
   */
  referrer?: string;
}

export interface AnalysisIsReadyProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
  /**
   * Analysis types selected by the user for the scan:
   *
   * * open source vulnerabilities
   *
   * * code quality issues
   *
   * * code security vulnerabilities
   *
   * * advisor issues
   *
   * * infrastructure as code issues
   *
   * * container vulnerabilities
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Snyk Advisor, Snyk Code Quality, Snyk Code Security, Snyk Open Source, Snyk Container, Snyk Infrastructure as Code |
   */
  analysisType:
    | "Snyk Advisor"
    | "Snyk Code Quality"
    | "Snyk Code Security"
    | "Snyk Open Source"
    | "Snyk Container"
    | "Snyk Infrastructure as Code";
  /**
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Success, Error |
   */
  result: "Success" | "Error";
}

export interface AnalysisIsTriggeredProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
  /**
   * Analysis types selected by the user for the scan: open source vulnerabilities, code quality issues and/or code security vulnerabilities.
   *
   * | Rule | Value |
   * |---|---|
   * | Min Items | 1 |
   * | Unique Items | true |
   * | Item Type | string |
   */
  analysisType: [string, ...string[]];
  /**
   * * True means that the analysis was triggered by the User.
   *
   * * False means that the analysis was triggered automatically by the plugin.
   */
  triggeredByUser: boolean;
}

export interface AuthenticateButtonIsClickedProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
  /**
   * Used to identify the source for multi-source events.
   *
   * For example, if a given event is shared between Snyk Advisor and Snyk Learn, this property helps to differentiate between the two.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Advisor, App, Learn, IDE |
   */
  eventSource?: "Advisor" | "App" | "Learn" | "IDE";
}

export interface IssueHoverIsDisplayedProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
  /**
   * Issue type
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Advisor, Code Quality Issue, Code Security Vulnerability, Licence Issue, Open Source Vulnerability, Infrastructure as Code Issue, Container Vulnerability |
   */
  issueType:
    | "Advisor"
    | "Code Quality Issue"
    | "Code Security Vulnerability"
    | "Licence Issue"
    | "Open Source Vulnerability"
    | "Infrastructure as Code Issue"
    | "Container Vulnerability";
  /**
   * Severity of the issue
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | High, Medium, Low, Critical |
   */
  severity: "High" | "Medium" | "Low" | "Critical";
  /**
   * Issue ID as received from the backend.
   */
  issueId: string;
}

export interface IssueInTreeIsClickedProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
  /**
   * Issue type
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Advisor, Code Quality Issue, Code Security Vulnerability, Licence Issue, Open Source Vulnerability, Infrastructure as Code Issue, Container Vulnerability |
   */
  issueType:
    | "Advisor"
    | "Code Quality Issue"
    | "Code Security Vulnerability"
    | "Licence Issue"
    | "Open Source Vulnerability"
    | "Infrastructure as Code Issue"
    | "Container Vulnerability";
  /**
   * Severity of the issue
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | High, Medium, Low, Critical |
   */
  severity: "High" | "Medium" | "Low" | "Critical";
  /**
   * Issue ID as received from the backend.
   */
  issueId: string;
}

export interface PluginIsInstalledProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
}

export interface PluginIsUninstalledProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
}

export interface QuickFixIsDisplayedProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
  /**
   * Quick fix types displayed to the user:
   *
   * * Show this suggestion
   *
   * * Ignore this particular suggestion
   *
   * * Ignore this suggestion in current file
   *
   * Due to array type definition limitation in Iteratively, the type is enforced in the code as follows:
   *
   * ```
   * type SupportedQuickFixProperties =
   * | 'Show Suggestion'
   * | 'Ignore Suggestion In Line'
   * | 'Ignore Suggestion In File';
   * ```
   *
   * | Rule | Value |
   * |---|---|
   * | Min Items | 1 |
   * | Unique Items | true |
   * | Item Type | string |
   */
  quickFixType: [string, ...string[]];
}

export interface WelcomeButtonIsClickedProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
  /**
   * Used to identify the source for multi-source events.
   *
   * For example, if a given event is shared between Snyk Advisor and Snyk Learn, this property helps to differentiate between the two.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Advisor, App, Learn, IDE |
   */
  eventSource?: "Advisor" | "App" | "Learn" | "IDE";
}

export interface WelcomeIsViewedProperties {
  /**
   * Ide family.
   *
   * | Rule | Value |
   * |---|---|
   * | Enum Values | Visual Studio Code, Visual Studio, Eclipse, JetBrains |
   */
  ide: "Visual Studio Code" | "Visual Studio" | "Eclipse" | "JetBrains";
}

export class AnalysisIsReady implements Event {
  name = 'Analysis Is Ready';
  id = 'c9337edb-27a3-416e-a654-092fa4375feb';
  version = '2.0.0';
  properties: AnalysisIsReadyProperties & {
    'itly': true;
  };

  constructor(
    properties: AnalysisIsReadyProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class AnalysisIsTriggered implements Event {
  name = 'Analysis Is Triggered';
  id = 'dabf569e-219c-470f-8e31-6e029723f0cd';
  version = '2.0.0';
  properties: AnalysisIsTriggeredProperties & {
    'itly': true;
  };

  constructor(
    properties: AnalysisIsTriggeredProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class AuthenticateButtonIsClicked implements Event {
  name = 'Authenticate Button Is Clicked';
  id = '2220c25f-ba76-4d5b-92f7-6d0e1c6165be';
  version = '1.0.0';
  properties: AuthenticateButtonIsClickedProperties & {
    'itly': true;
  };

  constructor(
    properties: AuthenticateButtonIsClickedProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class IssueHoverIsDisplayed implements Event {
  name = 'Issue Hover Is Displayed';
  id = '5bcc7fd8-6118-4777-b719-366cda263a13';
  version = '2.0.0';
  properties: IssueHoverIsDisplayedProperties & {
    'itly': true;
  };

  constructor(
    properties: IssueHoverIsDisplayedProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class IssueInTreeIsClicked implements Event {
  name = 'Issue In Tree Is Clicked';
  id = 'fae15d02-eab9-49bb-9833-18414e26058b';
  version = '2.0.0';
  properties: IssueInTreeIsClickedProperties & {
    'itly': true;
  };

  constructor(
    properties: IssueInTreeIsClickedProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class PluginIsInstalled implements Event {
  name = 'Plugin Is Installed';
  id = '7bb34693-366e-460e-8f4c-5b3f1c71888a';
  version = '1.0.0';
  properties: PluginIsInstalledProperties & {
    'itly': true;
  };

  constructor(
    properties: PluginIsInstalledProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class PluginIsUninstalled implements Event {
  name = 'Plugin Is Uninstalled';
  id = '5936cb0e-2639-4b76-baea-f0c086b860b0';
  version = '1.0.0';
  properties: PluginIsUninstalledProperties & {
    'itly': true;
  };

  constructor(
    properties: PluginIsUninstalledProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class QuickFixIsDisplayed implements Event {
  name = 'Quick Fix Is Displayed';
  id = '170c1284-9ee6-457f-aa82-6c49e49cde93';
  version = '1.0.0';
  properties: QuickFixIsDisplayedProperties & {
    'itly': true;
  };

  constructor(
    properties: QuickFixIsDisplayedProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class WelcomeButtonIsClicked implements Event {
  name = 'Welcome Button Is Clicked';
  id = 'e570e72e-4974-481a-9838-66cca471656b';
  version = '1.0.0';
  properties: WelcomeButtonIsClickedProperties & {
    'itly': true;
  };

  constructor(
    properties: WelcomeButtonIsClickedProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

export class WelcomeIsViewed implements Event {
  name = 'Welcome Is Viewed';
  id = '91114669-bbab-4f58-a7dd-ea7c98c79221';
  version = '1.0.0';
  properties: WelcomeIsViewedProperties & {
    'itly': true;
  };

  constructor(
    properties: WelcomeIsViewedProperties,
  ) {
    this.properties = {
        ...properties,
        'itly': true,
      };
  }
}

// prettier-ignore
interface DestinationOptions {

  all?: {
    disabled?: boolean;
  };
}

export interface LoadOptions extends OptionsBase {
  /**
   * Analytics provider-specific configuration.
   */
  destinations?: DestinationOptions;
}

// prettier-ignore
class Itly {
  private itly: ItlyNode;

  constructor() {
    this.itly = new ItlyNode();
  }

  /**
   * Initialize the Itly SDK. Call once when your application starts.
   * @param loadOptions Configuration options to initialize the Itly SDK with.
   */
  load(loadOptions: LoadOptions = {}) {
    const {
      destinations = {} as DestinationOptions,
      plugins = [] as Plugin[],
      ...options
    } = loadOptions;

    const destinationPlugins = destinations.all && destinations.all.disabled
      ? []
      : [

      ];

    this.itly.load({
      ...options,
      plugins: [
        new SchemaValidatorPlugin({
          'group': {"type":"object","properties":{"groupId":{"type":"string"},"name":{"type":"string"},"internalName":{"type":"string"},"groupType":{"enum":["org","group","account"]},"plan":{"type":"string"},"groupName":{"type":"string"},"projectTypes":{"type":"array","items":{"type":"string"},"uniqueItems":true}},"additionalProperties":false,"required":[]},
          'identify': {"type":"object","properties":{"isNonUser":{"type":"boolean"},"is_snyk":{"type":"boolean"},"utm_medium":{"type":"string"},"name":{"type":"string"},"utmMedium":{"type":"string"},"utm_campaign":{"type":"string"},"adminLink":{"type":"string"},"createdAt":{"type":"number"},"utmSource":{"type":"string"},"email":{"type":"string"},"accountType":{"enum":["user","service","app-instance"]},"authProvider":{"type":"string"},"isSnyk":{"type":"boolean"},"utm_source":{"type":"string"},"created_at":{"type":"number"},"auth_provider":{"type":"string"},"hasFirstProject":{"type":"boolean"},"isSnykAdmin":{"type":"boolean"},"user_id":{"type":"string"},"hasFirstIntegration":{"type":"boolean"},"admin_link":{"type":"string"},"username":{"type":"string"},"utmCampaign":{"type":"string"}},"additionalProperties":false,"required":[]},
          'page': {"type":"object","properties":{"package":{"type":"string"},"search":{"type":"string"},"url":{"type":"string"},"title":{"type":"string"},"path":{"type":"string"},"ecosystem":{"type":"string"},"referrer":{"type":"string"}},"additionalProperties":false,"required":[]},
          'Analysis Is Ready': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"itly":{"const":true},"analysisType":{"enum":["Snyk Advisor","Snyk Code Quality","Snyk Code Security","Snyk Open Source","Snyk Container","Snyk Infrastructure as Code"]},"result":{"enum":["Success","Error"]}},"additionalProperties":false,"required":["ide","itly","analysisType","result"]},
          'Analysis Is Triggered': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"itly":{"const":true},"analysisType":{"type":"array","items":{"type":"string"},"uniqueItems":true,"minItems":1},"triggeredByUser":{"type":"boolean"}},"additionalProperties":false,"required":["ide","itly","analysisType","triggeredByUser"]},
          'Authenticate Button Is Clicked': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"itly":{"const":true},"eventSource":{"enum":["Advisor","App","Learn","IDE"]}},"additionalProperties":false,"required":["ide","itly"]},
          'Issue Hover Is Displayed': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"issueType":{"enum":["Advisor","Code Quality Issue","Code Security Vulnerability","Licence Issue","Open Source Vulnerability","Infrastructure as Code Issue","Container Vulnerability"]},"severity":{"enum":["High","Medium","Low","Critical"]},"issueId":{"type":"string"},"itly":{"const":true}},"additionalProperties":false,"required":["ide","issueType","severity","issueId","itly"]},
          'Issue In Tree Is Clicked': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"issueType":{"enum":["Advisor","Code Quality Issue","Code Security Vulnerability","Licence Issue","Open Source Vulnerability","Infrastructure as Code Issue","Container Vulnerability"]},"severity":{"enum":["High","Medium","Low","Critical"]},"issueId":{"type":"string"},"itly":{"const":true}},"additionalProperties":false,"required":["ide","issueType","severity","issueId","itly"]},
          'Plugin Is Installed': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"itly":{"const":true}},"additionalProperties":false,"required":["ide","itly"]},
          'Plugin Is Uninstalled': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"itly":{"const":true}},"additionalProperties":false,"required":["ide","itly"]},
          'Quick Fix Is Displayed': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"itly":{"const":true},"quickFixType":{"type":"array","items":{"type":"string"},"uniqueItems":true,"minItems":1}},"additionalProperties":false,"required":["ide","itly","quickFixType"]},
          'Welcome Button Is Clicked': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"itly":{"const":true},"eventSource":{"enum":["Advisor","App","Learn","IDE"]}},"additionalProperties":false,"required":["ide","itly"]},
          'Welcome Is Viewed': {"type":"object","properties":{"ide":{"enum":["Visual Studio Code","Visual Studio","Eclipse","JetBrains"]},"itly":{"const":true}},"additionalProperties":false,"required":["ide","itly"]},
        }),
        ...destinationPlugins,
        ...plugins,
      ],
    });
  }

  /**
   * Alias a user ID to another user ID.
   * @param userId The user's new ID.
   * @param previousId The user's previous ID.
   * @param options Options for this alias call.
   */
  alias(userId: string, previousId: string, options?: AliasOptions) {
    this.itly.alias(userId, previousId, options);
  }

  /**
   * Identify a user and set or update that user's properties.
   * @param userId The user's ID.
   * @param properties The user's properties.
   * @param options Options for this identify call.
   */
  identify(
    userId: string,
    properties?: IdentifyProperties,
    options?: IdentifyOptions,
  ) {
    this.itly.identify(userId, properties, options)
  }

  /**
   * Associate a user with a group and set or update that group's properties.
   * @param userId The user's ID.
   * @param groupId The group's ID.
   * @param properties The group's properties.
   * @param options Options for this group call.
   */
  group(
    userId: string,
    groupId: string,
    properties?: GroupProperties,
    options?: GroupOptions,
  ) {
    this.itly.group(userId, groupId, properties, options)
  }

  /**
   * Triggered when the analysis is loaded within the IDE.
   * 
   * Owner: Georgi Mitev
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  analysisIsReady(
    userId: string,
    properties: AnalysisIsReadyProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new AnalysisIsReady(properties), options);
  }

  /**
   * User triggers an analysis or analysis is automatically triggered.
   * 
   * Owner: Georgi Mitev
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  analysisIsTriggered(
    userId: string,
    properties: AnalysisIsTriggeredProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new AnalysisIsTriggered(properties), options);
  }

  /**
   * This Event fires when the authenticate button is clicked.
   * 
   * Owner: Bastian Doetsch
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  authenticateButtonIsClicked(
    userId: string,
    properties: AuthenticateButtonIsClickedProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new AuthenticateButtonIsClicked(properties), options);
  }

  /**
   * Triggered when issue hover is displayed in the IDE editor.
   * 
   * Owner: Michel Kaporin
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  issueHoverIsDisplayed(
    userId: string,
    properties: IssueHoverIsDisplayedProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new IssueHoverIsDisplayed(properties), options);
  }

  /**
   * Triggered when the user selects an issue from the issues list and the issue is loaded.
   * 
   * Owner: Georgi Mitev
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  issueInTreeIsClicked(
    userId: string,
    properties: IssueInTreeIsClickedProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new IssueInTreeIsClicked(properties), options);
  }

  /**
   * Triggered when the user installs the plugin.
   * 
   * Owner: Georgi Mitev
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  pluginIsInstalled(
    userId: string,
    properties: PluginIsInstalledProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new PluginIsInstalled(properties), options);
  }

  /**
   * Triggered when the user uninstalls the plugin.
   * 
   * Owner: Georgi Mitev
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  pluginIsUninstalled(
    userId: string,
    properties: PluginIsUninstalledProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new PluginIsUninstalled(properties), options);
  }

  /**
   * Triggered when quick fix options are displayed to the user in IDE.
   * 
   * Owner: Michel Kaporin
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  quickFixIsDisplayed(
    userId: string,
    properties: QuickFixIsDisplayedProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new QuickFixIsDisplayed(properties), options);
  }

  /**
   * This event fires when the "Check it out" button is clicked in welcome notification.
   * 
   * Owner: Michel Kaporin
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  welcomeButtonIsClicked(
    userId: string,
    properties: WelcomeButtonIsClickedProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new WelcomeButtonIsClicked(properties), options);
  }

  /**
   * User installs the IDE plugin and see Snyk's welcome screen.
   * 
   * Owner: Georgi Mitev
   * @param userId The user's ID.
   * @param properties The event's properties (e.g. ide)
   * @param options Options for this track call.
   */
  welcomeIsViewed(
    userId: string,
    properties: WelcomeIsViewedProperties,
    options?: TrackOptions,
  ) {
    this.itly.track(userId, new WelcomeIsViewed(properties), options);
  }

  /**
   * Track any event.
   * @param userId The user's ID.
   * @param event The event to track.
   * @param options Options for this track call.
   */
  track(userId: string, event: Event, options?: TrackOptions) {
    this.itly.track(userId, event, options);
  }

  // reset() N/A for Node.js

  async flush() {
    await this.itly.flush();
  }
}

export default new Itly();
