name: Build and Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 2' # every Tuesday at 9 am UTC

jobs:
  build:
    uses: snyk/vscode-extension/.github/workflows/ci.yaml@main
    secrets:
      ITERATIVELY_KEY: ${{ secrets.ITERATIVELY_KEY }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment: Stable
    name: Publish extension
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup VSCE
        run: sudo npm install -g vsce@latest

      - name: Install dependencies
        run: npm install

      - name: Verify analytics events
        run: npm run ampli:verify -- -t ${{ secrets.ITERATIVELY_KEY }}

      - name: Add Credentials
        run: |
          sed -i \
              -e 's|${env.SNYK_VSCE_SEGMENT_WRITE_KEY}|${{ secrets.SNYK_VSCE_SEGMENT_WRITE_KEY }}|g' \
              -e 's|${env.SNYK_VSCE_AMPLITUDE_EXPERIMENT_API_KEY}|${{ secrets.SNYK_VSCE_AMPLITUDE_EXPERIMENT_API_KEY }}|g' \
              -e 's|${env.SNYK_VSCE_SENTRY_DSN_KEY}|${{ secrets.SNYK_VSCE_SENTRY_DSN_KEY }}|g' \
              snyk.config.json

      - name: Publish to Marketplace
        run: vsce publish -p ${{ secrets.MARKETPLACE_TOKEN }}

  release:
    runs-on: ubuntu-latest
    needs: publish
    environment: Stable
    name: Release
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Setup VSCE
        run: sudo npm install -g vsce@latest

      - name: Package VSIX
        run: echo y | vsce package

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1

      - name: Bump patch version
        id: patched-tag
        uses: anothrnick/github-tag-action@1.35.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.patched-tag.outputs.tag }}
          tag_name: ${{ steps.patched-tag.outputs.tag }}
          body: '${{ steps.extract-release-notes.outputs.release_notes }}'
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            **/*.vsix
